"""
Scaffolder — generates *.skill.yaml, *.patterns.yaml, and widget entries
from a live PostgreSQL table.
Uses schema_inspector lazily to avoid mandatory DB dependency at import time.
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any, NamedTuple

import structlog
import yaml

log = structlog.get_logger(__name__)

SCAFFOLD_HEADER = "# Auto-generated by dynamoui scaffold. Review all TODO fields before committing.\n"


class ScaffoldOutput(NamedTuple):
    skill_yaml: str
    patterns_yaml: str
    widgets: list[dict]


def _pascal_to_snake(name: str) -> str:
    """Convert PascalCase/camelCase identifier to snake_case. AlbumId → album_id"""
    s1 = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', name)
    return re.sub(r'([a-z\d])([A-Z])', r'\1_\2', s1).lower()


def _snake_to_entity(snake_name: str) -> str:
    """Convert snake_case to PascalCase entity name. invoice_line → InvoiceLine"""
    return "".join(word.capitalize() for word in snake_name.split("_"))


def _type_hint_for_pg_type(pg_type: str) -> str:
    """Map a PostgreSQL column type string to a DynamoUI skill field type."""
    pg_type = pg_type.lower()
    if "uuid" in pg_type:
        return "uuid"
    if any(t in pg_type for t in ("int", "serial", "bigint", "smallint")):
        return "integer"
    if any(t in pg_type for t in ("float", "real", "double", "numeric", "decimal")):
        return "float"
    if "bool" in pg_type:
        return "boolean"
    if any(t in pg_type for t in ("date", "timestamp", "time")):
        return "date"
    if "json" in pg_type:
        return "json"
    return "string"


def _normalize_pattern(p: dict) -> dict:
    """
    Normalise an LLM-generated pattern dict to satisfy PatternFile validation:
    - query_template must be a JSON string, not a dict
    - param default values must be str or None, not int/float/bool
    """
    import json as _json
    p = dict(p)
    if isinstance(p.get("query_template"), dict):
        p["query_template"] = _json.dumps(p["query_template"])
    if p.get("params"):
        normalised_params = []
        for param in p["params"]:
            param = dict(param)
            default = param.get("default")
            if default is not None and not isinstance(default, str):
                param["default"] = str(default)
            normalised_params.append(param)
        p["params"] = normalised_params
    return p


def _compute_hash(content: str, length: int = 16) -> str:
    """SHA-256 of content string, truncated to length chars (matches PatternHasher)."""
    return hashlib.sha256(content.encode()).hexdigest()[:length]


def _build_patterns(entity: str, snake_table: str, columns: list[dict[str, Any]]) -> list[dict]:
    """
    Build scaffold pattern dicts from raw PG column descriptors.
    Always produces a 'list_all' pattern; adds per-field search patterns
    for string columns whose names contain common name-like keywords.

    pattern IDs use the snake_case table name as prefix (e.g. invoice_line.list_all).
    filter fields reference the snake_case field name.
    """
    pattern_prefix = snake_table  # snake_case for pattern IDs
    entity_lower = entity.lower()
    entity_plural = f"{snake_table}s"  # simple plural of snake_case name

    patterns: list[dict] = [
        {
            "id": f"{pattern_prefix}.list_all",
            "description": f"List all {entity} records",
            "triggers": [
                f"all {entity_plural}",
                f"show all {entity_plural}",
                f"list {entity_plural}",
                f"get all {entity_plural}",
            ],
            "query_template": '{"filters": []}',
            "params": [],
        }
    ]

    name_keywords = ("name", "title", "email", "code", "label")
    for col in columns:
        if col.get("is_pk"):
            continue
        if _type_hint_for_pg_type(col["type"]) != "string":
            continue
        col_name = col["name"]
        snake_col = _pascal_to_snake(col_name)
        if not any(kw in snake_col for kw in name_keywords):
            continue
        patterns.append({
            "id": f"{pattern_prefix}.by_{snake_col}",
            "description": f"Search {entity} by {snake_col.replace('_', ' ').title()}",
            "triggers": [
                f"{entity_lower} {snake_col.replace('_', ' ')}",
                f"find {entity_lower} by {snake_col.replace('_', ' ')}",
                f"search {entity_lower} {snake_col.replace('_', ' ')}",
            ],
            "query_template": json.dumps({
                "filters": [{"field": snake_col, "op": "like", "value": f"{{{snake_col}}}"}]
            }),
            "params": [{"name": snake_col, "type": "string", "required": True}],
        })

    return patterns


def _build_role_context_section(entity: str, role_context: list[dict]) -> str:
    """
    Build the 'Business use cases' prompt section from scoped role/query pairs.

    role_context: list of {role: str, queries: list[str]} already filtered to this entity.
    Returns empty string if role_context is empty.
    """
    if not role_context:
        return ""
    lines = ["\nBusiness use cases:"]
    for entry in role_context:
        lines.append(f"{entry['role']} asks:")
        for q in entry["queries"]:
            lines.append(f'  - "{q}"')
    lines.append(
        "\nGenerate patterns that address these use cases directly. "
        "Each query above should map to at least one pattern with that query "
        "(or a close paraphrase) as a trigger."
    )
    return "\n".join(lines)


def _widget_for_pattern(
    snake_table: str,
    entity: str,
    pattern: dict,
    role_context: list[dict],
) -> dict:
    """
    Build a widget dict for a pattern.
    If the pattern trigger matches a role query, use the role name as category
    and the original query string as title.
    Falls back to entity name + description-derived title.
    """
    pattern_id = pattern["id"]
    pattern_name = pattern_id.split(".")[-1]
    triggers = set(t.lower().strip() for t in pattern.get("triggers", []))

    matched_role: str | None = None
    matched_query: str | None = None
    for entry in role_context:
        for q in entry["queries"]:
            if q.lower().strip() in triggers:
                matched_role = entry["role"]
                matched_query = q
                break
        if matched_role:
            break

    if matched_role and matched_query:
        category = matched_role
        title = matched_query
    else:
        category = entity
        title = pattern.get("description") or pattern_name.replace("_", " ").title()

    return {
        "id": f"{snake_table}_{pattern_name}",
        "title": title,
        "description": pattern.get("description", ""),
        "entity": entity,
        "pattern_id": pattern_id,
        "category": category,
        "icon": "table",
        "params": pattern.get("params", []),
    }


async def scaffold_from_columns(
    table: str,
    schema: str,
    adapter_key: str,
    columns: list[dict[str, Any]],
    output_dir: Path | None = None,
    *,
    table_comment: str = "",
    llm_seeder: "PatternSeeder | None" = None,
    full_schema_context: str = "",
    role_context: list[dict] | None = None,
) -> ScaffoldOutput:
    """
    Build a ScaffoldOutput (skill YAML, patterns YAML, widget entries)
    from a list of column descriptors.

    Each column dict must have:
      - name: str
      - type: str (PostgreSQL type)
      - nullable: bool
      - is_pk: bool
    Optional per-column fields (from SchemaInspector):
      - comment: str — column description (semantic tag already stripped)
      - semantic: str | None — parsed semantic tag value

    table_comment: COMMENT ON TABLE text; maps to business_description when non-empty.
    role_context: list of {role: str, queries: list[str]} scoped to this entity.
    """
    _role_context = role_context or []

    # Derive snake_case table name and PascalCase entity name
    snake_table = _pascal_to_snake(table) if not re.match(r'^[a-z][a-z0-9_]*$', table) else table
    entity = _snake_to_entity(snake_table)
    # Store the original DB table name if it differs from snake_case
    db_table_name = table if table != snake_table else ""

    # ── skill YAML ────────────────────────────────────────────────────────────
    fields: list[dict] = []
    for col in columns:
        col_name = col["name"]
        snake_col = _pascal_to_snake(col_name) if not re.match(r'^[a-z][a-z0-9_]*$', col_name) else col_name
        field_type = _type_hint_for_pg_type(col["type"])
        field_def: dict = {
            "name": snake_col,
            "type": field_type,
            "nullable": col.get("nullable", True),
            "isPK": col.get("is_pk", False),
        }
        if col.get("is_pk"):
            field_def["nullable"] = False
        if col_name != snake_col:
            field_def["db_column_name"] = col_name
        if field_type == "enum":
            field_def["enumRef"] = "# TODO: set enum name"
        # Map column comment → description (omit key if empty)
        col_comment = col.get("comment", "").strip()
        if col_comment:
            field_def["description"] = col_comment
        # Map semantic tag (omit key if None)
        col_semantic = col.get("semantic")
        if col_semantic:
            field_def["semantic"] = col_semantic
        fields.append(field_def)

    patterns_filename = f"{snake_table}.patterns.yaml"
    if output_dir is not None:
        patterns_file_path = str(output_dir / patterns_filename)
    else:
        patterns_file_path = patterns_filename

    skill_data: dict = {
        "entity": entity,
        "table": snake_table,
        "adapter": adapter_key,
        "schema_name": schema,
        "fields": fields,
        "display": {
            "default_sort_field": fields[0]["name"] if fields else "",
            "default_sort_dir": "asc",
            "columns_visible": [f["name"] for f in fields[:8]],
            "detail_fields": [f["name"] for f in fields],
            "searchable_fields": [],
            "page_size": 25,
        },
        "mutations_file": "",
        "patterns_file": patterns_file_path,
        "read_permissions": [],
        "write_permissions": [],
    }

    # business_description: use table comment when present, omit key entirely otherwise
    if table_comment:
        skill_data["business_description"] = table_comment
    else:
        # No TODO placeholder — omit the key entirely per spec
        skill_data["description"] = ""

    if db_table_name:
        skill_data["db_table_name"] = db_table_name

    skill_yaml = SCAFFOLD_HEADER + yaml.dump(
        skill_data, default_flow_style=False, sort_keys=False, allow_unicode=True
    )

    # ── patterns YAML ─────────────────────────────────────────────────────────
    skill_hash = _compute_hash(skill_yaml)
    patterns = _build_patterns(entity, snake_table, columns)

    if llm_seeder is not None:
        ctx = full_schema_context or llm_seeder.build_full_schema_context(
            {entity: skill_yaml}, {}
        )
        role_section = _build_role_context_section(entity, _role_context)
        llm_patterns = await llm_seeder.seed_patterns(entity, skill_yaml, ctx, role_section=role_section)
        if llm_patterns:
            existing_ids = {p["id"] for p in patterns}
            for lp in llm_patterns:
                if lp.get("id") and lp["id"] not in existing_ids:
                    patterns.append(_normalize_pattern(lp))
                    existing_ids.add(lp["id"])
            log.info("scaffolder.llm_patterns_merged",
                     entity=entity, count=len(llm_patterns))

    # Write domain_roles back into skill YAML if role_context was used
    if _role_context:
        # Strip comment header lines before parsing YAML
        yaml_body = "\n".join(
            line for line in skill_yaml.splitlines() if not line.startswith("#")
        )
        skill_raw = yaml.safe_load(yaml_body) or {}
        skill_raw["domain_roles"] = [
            {"role": e["role"], "typical_queries": e["queries"]} for e in _role_context
        ]
        skill_yaml = SCAFFOLD_HEADER + yaml.dump(
            skill_raw, default_flow_style=False, sort_keys=False, allow_unicode=True
        )
        # Recompute hash since skill YAML changed
        skill_hash = _compute_hash(skill_yaml)

    patterns_data = {"entity": entity, "patterns": patterns}
    patterns_yaml = (
        f"# skill_hash: {skill_hash}\n"
        "# Auto-generated by dynamoui scaffold. Review triggers and extend before committing.\n"
        + yaml.dump(patterns_data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    )

    # ── widget entries ────────────────────────────────────────────────────────
    widgets: list[dict] = []
    for pattern in patterns:
        widgets.append(_widget_for_pattern(snake_table, entity, pattern, _role_context))

    log.info(
        "scaffolder.generated",
        entity=entity,
        table=snake_table,
        db_table_name=db_table_name or snake_table,
        fields=len(fields),
        patterns=len(patterns),
        widgets=len(widgets),
    )
    return ScaffoldOutput(skill_yaml=skill_yaml, patterns_yaml=patterns_yaml, widgets=widgets)


def _merge_llm_patterns(
    output: ScaffoldOutput,
    entity: str,
    llm_patterns: list[dict],
    role_context: list[dict] | None = None,
) -> tuple[ScaffoldOutput, list[dict]]:
    """
    Merge LLM-generated patterns into an existing ScaffoldOutput.
    Returns the updated ScaffoldOutput and the list of newly added widgets.
    """
    _role_context = role_context or []

    # Parse the existing patterns_yaml, skipping header lines
    lines = output.patterns_yaml.split("\n")
    skip = sum(
        1 for line in lines[:2]
        if line.startswith("# skill_hash:") or line.startswith("# Auto-generated")
    )
    header = "\n".join(lines[:skip])
    body = "\n".join(lines[skip:])
    raw = yaml.safe_load(body) or {}
    raw.setdefault("patterns", [])

    # Derive snake_table from entity name for widget IDs
    snake_table = _pascal_to_snake(entity)

    existing_ids = {p["id"] for p in raw["patterns"]}
    added: list[dict] = []
    for lp in llm_patterns:
        if lp.get("id") and lp["id"] not in existing_ids:
            lp = _normalize_pattern(lp)
            raw["patterns"].append(lp)
            existing_ids.add(lp["id"])
            added.append(lp)

    if not added:
        return output, []

    new_patterns_yaml = (
        (header + "\n" if header else "")
        + yaml.dump(raw, default_flow_style=False, sort_keys=False, allow_unicode=True)
    )
    new_widgets = []
    for lp in added:
        new_widgets.append(_widget_for_pattern(snake_table, entity, lp, _role_context))

    updated = ScaffoldOutput(
        skill_yaml=output.skill_yaml,
        patterns_yaml=new_patterns_yaml,
        widgets=list(output.widgets) + new_widgets,
    )
    return updated, new_widgets


async def scaffold_table(
    adapter_key: str,
    table_name: str,
    schema_name: str = "public",
    output_dir: Path | None = None,
    *,
    llm_seeder: "PatternSeeder | None" = None,
    full_schema_context: str = "",
    role_context: list[dict] | None = None,
    metering_service: "MeteringService | None" = None,
) -> ScaffoldOutput:
    """
    Inspect a live PostgreSQL table and return a ScaffoldOutput.
    Requires an active adapter connection.
    """
    import time as _time
    from backend.adapters.postgresql.schema_inspector import SchemaInspector

    inspector = SchemaInspector(adapter_key)
    columns, table_comment = await inspector.inspect_table(table_name, schema_name)

    operation_id = None
    metering_ctx_token = None
    t0 = _time.monotonic()

    if metering_service is not None and llm_seeder is not None:
        from backend.metering.context import MeteringContext, clear_metering_context, set_metering_context
        from backend.metering.dto.operation_dto import OperationUpdateDTO
        operation_id = await metering_service.start_operation(
            operation_type="scaffold_table",
            metadata={"table": table_name, "schema": schema_name},
        )
        metering_ctx_token = set_metering_context(
            MeteringContext(
                operation_id=operation_id,
                interaction_type="pattern_seeding",
            )
        )

    try:
        return await scaffold_from_columns(
            table_name, schema_name, adapter_key, columns,
            output_dir,
            table_comment=table_comment,
            llm_seeder=llm_seeder,
            full_schema_context=full_schema_context,
            role_context=role_context,
        )
    finally:
        if metering_ctx_token is not None:
            from backend.metering.context import clear_metering_context
            clear_metering_context(metering_ctx_token)
        if metering_service is not None and operation_id is not None:
            from backend.metering.dto.operation_dto import OperationUpdateDTO
            await metering_service.complete_operation(
                operation_id,
                OperationUpdateDTO(
                    entity=table_name,
                    success=True,
                    duration_ms=int((_time.monotonic() - t0) * 1000),
                ),
            )


async def scaffold_schema(
    adapter_key: str,
    schema_name: str = "public",
    output_dir: Path | None = None,
    *,
    llm_seeder: "PatternSeeder | None" = None,
    llm_batch_size: int = 5,
    role_context_map: dict[str, list[dict]] | None = None,
    metering_service: "MeteringService | None" = None,
) -> dict[str, ScaffoldOutput]:
    """
    Inspect all tables in a PostgreSQL schema and return {table_name: ScaffoldOutput}.
    If output_dir is provided, writes *.skill.yaml, *.patterns.yaml, and widgets.yaml to disk.

    role_context_map: {entity_name: [{role, queries}]} pre-built from the context file.

    When llm_seeder is provided:
    - Single DB pass to scaffold all tables with heuristic patterns.
    - Batch LLM calls (llm_batch_size entities per call) to generate cross-entity patterns.
    - LLM-generated patterns are merged into the heuristic results in-memory.
    This produces ceil(N/llm_batch_size) LLM calls instead of N calls.
    """
    import re as _re
    import yaml as _yaml_mod
    from backend.adapters.postgresql.schema_inspector import SchemaInspector

    _role_context_map = role_context_map or {}

    inspector = SchemaInspector(adapter_key)
    tables = await inspector.list_tables(schema_name)
    results: dict[str, ScaffoldOutput] = {}
    all_widgets: list[dict] = []

    # Single DB pass — heuristic scaffold for all tables
    for table in tables:
        snake = _pascal_to_snake(table) if not _re.match(r'^[a-z][a-z0-9_]*$', table) else table
        entity = _snake_to_entity(snake)
        entity_role_ctx = _role_context_map.get(entity, [])
        output = await scaffold_table(
            adapter_key, table, schema_name, output_dir,
            role_context=entity_role_ctx,
        )
        results[table] = output
        all_widgets.extend(output.widgets)

    if llm_seeder is not None:
        # Build entity map and full schema context from heuristic results
        table_to_entity: dict[str, str] = {}
        all_skill_yamls: dict[str, str] = {}
        for table, out in results.items():
            snake = _pascal_to_snake(table) if not _re.match(r'^[a-z][a-z0-9_]*$', table) else table
            entity = _snake_to_entity(snake)
            table_to_entity[table] = entity
            all_skill_yamls[entity] = out.skill_yaml

        fk_edges: dict[str, list] = {}
        for entity_name, skill_yaml_str in all_skill_yamls.items():
            raw = _yaml_mod.safe_load(skill_yaml_str) or {}
            edges = []
            for f in raw.get("fields", []):
                fk = f.get("fk")
                if fk:
                    edges.append((f["name"], fk.get("entity", ""), fk.get("field", "")))
            fk_edges[entity_name] = edges

        full_schema_context = llm_seeder.build_full_schema_context(all_skill_yamls, fk_edges)

        # Batch LLM calls — ceil(N / llm_batch_size) total calls
        table_list = list(tables)
        for i in range(0, len(table_list), llm_batch_size):
            import time as _time
            batch_tables = table_list[i:i + llm_batch_size]
            batch_skill_yamls = {
                table_to_entity[t]: all_skill_yamls[table_to_entity[t]]
                for t in batch_tables
            }

            # Metering: open an operation for this batch LLM call
            _batch_op_id = None
            _batch_ctx_token = None
            _batch_t0 = _time.monotonic()
            if metering_service is not None:
                from backend.metering.context import MeteringContext, clear_metering_context, set_metering_context
                from backend.metering.dto.operation_dto import OperationUpdateDTO
                _batch_op_id = await metering_service.start_operation(
                    operation_type="scaffold_schema",
                    metadata={
                        "schema": schema_name,
                        "batch": i // llm_batch_size + 1,
                        "entities": list(batch_skill_yamls.keys()),
                    },
                )
                _batch_ctx_token = set_metering_context(
                    MeteringContext(
                        operation_id=_batch_op_id,
                        interaction_type="pattern_seeding",
                    )
                )

            try:
                batch_patterns = await llm_seeder.seed_patterns_batch(
                    batch_skill_yamls, full_schema_context, role_context_map=_role_context_map
                )
            finally:
                if _batch_ctx_token is not None:
                    from backend.metering.context import clear_metering_context
                    clear_metering_context(_batch_ctx_token)
                if metering_service is not None and _batch_op_id is not None:
                    from backend.metering.dto.operation_dto import OperationUpdateDTO
                    await metering_service.complete_operation(
                        _batch_op_id,
                        OperationUpdateDTO(
                            success=True,
                            duration_ms=int((_time.monotonic() - _batch_t0) * 1000),
                        ),
                    )
            log.info(
                "scaffolder.llm_batch_complete",
                batch=i // llm_batch_size + 1,
                entities=list(batch_skill_yamls.keys()),
                returned_entities=list(batch_patterns.keys()),
            )

            # Merge LLM patterns into results for each table in this batch
            for table in batch_tables:
                entity = table_to_entity[table]
                llm_pats = batch_patterns.get(entity, [])
                if not llm_pats:
                    continue
                entity_role_ctx = _role_context_map.get(entity, [])
                results[table], new_widgets = _merge_llm_patterns(
                    results[table], entity, llm_pats, role_context=entity_role_ctx
                )
                # Replace widgets for this table in all_widgets
                all_widgets = [w for w in all_widgets if w.get("entity") != entity]
                all_widgets.extend(results[table].widgets)
                log.info("scaffolder.llm_patterns_merged",
                         entity=entity, count=len(llm_pats))

    # Write all skill + patterns files
    if output_dir is not None:
        import re as _re
        for table, out in results.items():
            snake_table = _pascal_to_snake(table) if not _re.match(r'^[a-z][a-z0-9_]*$', table) else table
            skill_path = output_dir / f"{snake_table}.skill.yaml"
            skill_path.write_text(out.skill_yaml, encoding="utf-8")
            log.info("scaffolder.skill_written", path=str(skill_path))
            patterns_path = output_dir / f"{snake_table}.patterns.yaml"
            patterns_path.write_text(out.patterns_yaml, encoding="utf-8")
            log.info("scaffolder.patterns_written", path=str(patterns_path))

    if output_dir is not None and all_widgets:
        widgets_path = output_dir / "widgets.yaml"
        widgets_yaml = yaml.dump(
            {"widgets": all_widgets},
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )
        widgets_path.write_text(widgets_yaml, encoding="utf-8")
        log.info("scaffolder.widgets_written", path=str(widgets_path), count=len(all_widgets))

    return results
