"""
Scaffolder — generates *.skill.yaml, *.patterns.yaml, and widget entries
from a live PostgreSQL table.
Uses schema_inspector lazily to avoid mandatory DB dependency at import time.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, NamedTuple

import structlog
import yaml

log = structlog.get_logger(__name__)

SCAFFOLD_HEADER = "# Auto-generated by dynamoui scaffold. Review all TODO fields before committing.\n"


class ScaffoldOutput(NamedTuple):
    skill_yaml: str
    patterns_yaml: str
    widgets: list[dict]


def _type_hint_for_pg_type(pg_type: str) -> str:
    """Map a PostgreSQL column type string to a DynamoUI skill field type."""
    pg_type = pg_type.lower()
    if "uuid" in pg_type:
        return "uuid"
    if any(t in pg_type for t in ("int", "serial", "bigint", "smallint")):
        return "integer"
    if any(t in pg_type for t in ("float", "real", "double", "numeric", "decimal")):
        return "float"
    if "bool" in pg_type:
        return "boolean"
    if any(t in pg_type for t in ("date", "timestamp", "time")):
        return "date"
    if "json" in pg_type:
        return "json"
    return "string"


def _compute_hash(content: str, length: int = 16) -> str:
    """SHA-256 of content string, truncated to length chars (matches PatternHasher)."""
    return hashlib.sha256(content.encode()).hexdigest()[:length]


def _build_patterns(entity: str, columns: list[dict[str, Any]]) -> list[dict]:
    """
    Build scaffold pattern dicts from raw PG column descriptors.
    Always produces a 'list_all' pattern; adds per-field search patterns
    for string columns whose names contain common name-like keywords.
    """
    entity_lower = entity.lower()
    entity_plural = f"{entity_lower}s"

    patterns: list[dict] = [
        {
            "id": f"{entity_lower}.list_all",
            "description": f"List all {entity} records",
            "triggers": [
                f"all {entity_plural}",
                f"show all {entity_plural}",
                f"list {entity_plural}",
                f"get all {entity_plural}",
            ],
            "query_template": '{"filters": []}',
            "params": [],
        }
    ]

    name_keywords = ("name", "title", "email", "code", "label")
    for col in columns:
        if col.get("is_pk"):
            continue
        if _type_hint_for_pg_type(col["type"]) != "string":
            continue
        col_name = col["name"]
        col_lower = col_name.lower()
        if not any(kw in col_lower for kw in name_keywords):
            continue
        patterns.append({
            "id": f"{entity_lower}.by_{col_lower}",
            "description": f"Search {entity} by {col_name}",
            "triggers": [
                f"{entity_lower} {col_lower}",
                f"find {entity_lower} by {col_lower}",
                f"search {entity_lower} {col_lower}",
            ],
            "query_template": json.dumps({
                "filters": [{"field": col_name, "op": "ilike", "value": f"{{{col_lower}}}"}]
            }),
            "params": [{"name": col_lower, "type": "string", "required": True}],
        })

    return patterns


def scaffold_from_columns(
    table: str,
    schema: str,
    adapter_key: str,
    columns: list[dict[str, Any]],
) -> ScaffoldOutput:
    """
    Build a ScaffoldOutput (skill YAML, patterns YAML, widget entries)
    from a list of column descriptors.

    Each column dict must have:
      - name: str
      - type: str (PostgreSQL type)
      - nullable: bool
      - is_pk: bool
    """
    entity = "".join(word.capitalize() for word in table.split("_"))

    # ── skill YAML ────────────────────────────────────────────────────────────
    fields: list[dict] = []
    for col in columns:
        field_type = _type_hint_for_pg_type(col["type"])
        field_def: dict = {
            "name": col["name"],
            "type": field_type,
            "nullable": col.get("nullable", True),
            "isPK": col.get("is_pk", False),
        }
        if col.get("is_pk"):
            field_def["nullable"] = False
        if field_type == "enum":
            field_def["enumRef"] = "# TODO: set enum name"
        fields.append(field_def)

    patterns_filename = f"{table}.patterns.yaml"
    skill_data: dict = {
        "entity": entity,
        "table": table,
        "adapter": adapter_key,
        "description": f"# TODO: describe {entity}",
        "schema_name": schema,
        "fields": fields,
        "display": {
            "default_sort_field": fields[0]["name"] if fields else "",
            "default_sort_dir": "asc",
            "columns_visible": [f["name"] for f in fields[:8]],
            "detail_fields": [f["name"] for f in fields],
            "searchable_fields": [],
            "page_size": 25,
        },
        "mutations_file": "# TODO: set path or leave empty for read-only",
        "patterns_file": patterns_filename,
        "read_permissions": [],
        "write_permissions": [],
    }

    skill_yaml = SCAFFOLD_HEADER + yaml.dump(
        skill_data, default_flow_style=False, sort_keys=False, allow_unicode=True
    )

    # ── patterns YAML ─────────────────────────────────────────────────────────
    skill_hash = _compute_hash(skill_yaml)
    patterns = _build_patterns(entity, columns)
    patterns_data = {"entity": entity, "patterns": patterns}
    patterns_yaml = (
        f"# skill_hash: {skill_hash}\n"
        "# Auto-generated by dynamoui scaffold. Review triggers and extend before committing.\n"
        + yaml.dump(patterns_data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    )

    # ── widget entries ────────────────────────────────────────────────────────
    entity_lower = entity.lower()
    widgets: list[dict] = []
    for pattern in patterns:
        pattern_id = pattern["id"]
        pattern_name = pattern_id.split(".")[-1]
        widgets.append({
            "id": f"{entity_lower}_{pattern_name}",
            "title": f"{entity} — {pattern_name.replace('_', ' ').title()}",
            "description": pattern.get("description", ""),
            "entity": entity,
            "pattern_id": pattern_id,
            "category": "# TODO: set category",
            "icon": "table",
            "params": pattern.get("params", []),
        })

    log.info(
        "scaffolder.generated",
        entity=entity,
        table=table,
        fields=len(fields),
        patterns=len(patterns),
        widgets=len(widgets),
    )
    return ScaffoldOutput(skill_yaml=skill_yaml, patterns_yaml=patterns_yaml, widgets=widgets)


async def scaffold_table(
    adapter_key: str,
    table_name: str,
    schema_name: str = "public",
) -> ScaffoldOutput:
    """
    Inspect a live PostgreSQL table and return a ScaffoldOutput.
    Requires an active adapter connection.
    """
    from backend.adapters.postgresql.schema_inspector import SchemaInspector

    inspector = SchemaInspector(adapter_key)
    columns = await inspector.inspect_table(table_name, schema_name)
    return scaffold_from_columns(table_name, schema_name, adapter_key, columns)


async def scaffold_schema(
    adapter_key: str,
    schema_name: str = "public",
    output_dir: Path | None = None,
) -> dict[str, ScaffoldOutput]:
    """
    Inspect all tables in a PostgreSQL schema and return {table_name: ScaffoldOutput}.
    If output_dir is provided, writes *.skill.yaml, *.patterns.yaml, and widgets.yaml to disk.
    """
    from backend.adapters.postgresql.schema_inspector import SchemaInspector

    inspector = SchemaInspector(adapter_key)
    tables = await inspector.list_tables(schema_name)
    results: dict[str, ScaffoldOutput] = {}
    all_widgets: list[dict] = []

    for table in tables:
        output = await scaffold_table(adapter_key, table, schema_name)
        results[table] = output
        all_widgets.extend(output.widgets)

        if output_dir is not None:
            skill_path = output_dir / f"{table}.skill.yaml"
            skill_path.write_text(output.skill_yaml, encoding="utf-8")
            log.info("scaffolder.skill_written", path=str(skill_path))

            patterns_path = output_dir / f"{table}.patterns.yaml"
            patterns_path.write_text(output.patterns_yaml, encoding="utf-8")
            log.info("scaffolder.patterns_written", path=str(patterns_path))

    if output_dir is not None and all_widgets:
        widgets_path = output_dir / "widgets.yaml"
        widgets_yaml = yaml.dump(
            {"widgets": all_widgets},
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )
        widgets_path.write_text(widgets_yaml, encoding="utf-8")
        log.info("scaffolder.widgets_written", path=str(widgets_path), count=len(all_widgets))

    return results
