"""CanvasDomainPatternSeeder — domain-aware NL trigger templates (LLD 9 §10).

Reads ./backend/canvas/domain_patterns/{domain}.yaml and substitutes
{entity} → entity label per row in entity_priorities. Confidence 0.75 — below
the auto-promote threshold so the existing PatternPromoter handles promotion.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from backend.canvas.models.intent import CanvasIntent


@dataclass
class SeededPattern:
    """Lightweight pattern tuple. The router/generator hands this to the
    real PatternSeeder.from_template() at integration time so we don't take
    a hard dep on its current Pydantic shape."""

    nl_trigger: str
    entity: str
    intent: str
    confidence: float = 0.75
    source: str = "domain_seed"
    metadata: dict[str, Any] = field(default_factory=dict)


class CanvasDomainPatternSeeder:
    def __init__(self, patterns_dir: Path | str) -> None:
        self._dir = Path(patterns_dir)

    def seed(
        self,
        intent: CanvasIntent,
        entity_label_resolver=lambda name: name,
    ) -> list[SeededPattern]:
        """Resolve entity labels via the supplied callable (default: identity)."""
        if intent.domain is None:
            return []
        domain_file = self._dir / f"{intent.domain.value}.yaml"
        if not domain_file.exists():
            return []
        templates = yaml.safe_load(domain_file.read_text(encoding="utf-8")) or {}
        rows = templates.get("patterns", []) or []
        out: list[SeededPattern] = []
        for entity_name in intent.entity_priorities or []:
            label = entity_label_resolver(entity_name) or entity_name
            for row in rows:
                tmpl = row.get("template", "")
                if not tmpl:
                    continue
                out.append(
                    SeededPattern(
                        nl_trigger=tmpl.replace("{entity}", label),
                        entity=entity_name,
                        intent=row.get("intent", "READ"),
                        metadata={
                            "domain": intent.domain.value,
                            "entity_hint": row.get("entity_hint"),
                        },
                    )
                )
        return out

    def to_yaml(self, patterns: list[SeededPattern], entity: str) -> str:
        """Serialise to a *.patterns.yaml fragment."""
        body = {
            "entity": entity,
            "patterns": [
                {
                    "nl_trigger": p.nl_trigger,
                    "intent": p.intent,
                    "confidence": p.confidence,
                    "source": p.source,
                }
                for p in patterns
                if p.entity == entity
            ],
        }
        header = (
            f"# {entity}.patterns.yaml — generated by DynamoUI Canvas (domain seed)\n"
            "# DO NOT EDIT — re-run Canvas to regenerate\n"
        )
        return header + yaml.safe_dump(body, sort_keys=False, default_flow_style=False)
