"""LayoutSynthesiser — CanvasIntent → LayoutConfig + YAML (LLD 9 §8)."""
from __future__ import annotations

import yaml

from backend.canvas.models.intent import (
    AestheticMood,
    CanvasIntent,
    LayoutArchetype,
    LayoutConfig,
    NavStyle,
    OperationProfile,
)
from backend.canvas.synthesis.theme_synthesiser import CanvasValidationError


SIDEBAR_MOODS = {
    AestheticMood.ENTERPRISE,
    AestheticMood.FUNCTIONAL,
    AestheticMood.CLINICAL,
}

MAX_SIDEBAR_ENTITIES = 3
MAX_METRIC_FIELDS = 4


class LayoutSynthesiser:
    def synthesise(self, intent: CanvasIntent) -> LayoutConfig:
        if intent.primary_entity is None:
            raise CanvasValidationError("primary_entity is required for layout synthesis")
        if intent.density is None:
            raise CanvasValidationError("density is required for layout synthesis")

        archetype = self._select_archetype(intent)
        nav = self._select_nav(intent)

        sidebar_pool = [
            e for e in intent.entity_priorities if e != intent.primary_entity
        ]
        sidebar = sidebar_pool[:MAX_SIDEBAR_ENTITIES]
        metrics = list(intent.key_monetary_fields[:MAX_METRIC_FIELDS])

        return LayoutConfig(
            archetype=archetype,
            nav_style=nav,
            primary_entity=intent.primary_entity,
            sidebar_entities=sidebar,
            metric_card_fields=metrics,
            bulk_action_enabled=intent.operation_profile in (
                OperationProfile.REVIEW_AUDIT, OperationProfile.MIXED,
            ),
            export_enabled=intent.operation_profile in (
                OperationProfile.READ_HEAVY, OperationProfile.MIXED,
            ),
            density=intent.density,
        )

    @staticmethod
    def _select_archetype(intent: CanvasIntent) -> LayoutArchetype:
        # Kanban + timeline take priority over op-profile-derived archetypes.
        if intent.enable_kanban:
            return LayoutArchetype.KANBAN
        if intent.enable_timeline:
            return LayoutArchetype.TIMELINE
        if intent.operation_profile == OperationProfile.READ_HEAVY:
            return LayoutArchetype.DASHBOARD
        if intent.operation_profile == OperationProfile.WRITE_HEAVY:
            return LayoutArchetype.DATA_ENTRY
        if intent.operation_profile == OperationProfile.REVIEW_AUDIT:
            return LayoutArchetype.REVIEW_AUDIT
        return LayoutArchetype.DASHBOARD

    @staticmethod
    def _select_nav(intent: CanvasIntent) -> NavStyle:
        if intent.aesthetic_mood in SIDEBAR_MOODS:
            return NavStyle.SIDEBAR
        return NavStyle.TOP_NAV

    @staticmethod
    def to_yaml(config: LayoutConfig) -> str:
        body = {
            "canvas_version": "1.0",
            "archetype": config.archetype.value,
            "nav_style": config.nav_style.value,
            "primary_entity": config.primary_entity,
            "sidebar_entities": config.sidebar_entities,
            "metric_card_fields": config.metric_card_fields,
            "bulk_action_enabled": config.bulk_action_enabled,
            "export_enabled": config.export_enabled,
            "density": config.density.value,
        }
        header = (
            "# layout.config.yaml — generated by DynamoUI Canvas\n"
            "# DO NOT EDIT — re-run Canvas to regenerate\n"
        )
        return header + yaml.safe_dump(body, sort_keys=False, default_flow_style=False)
