"""
Schema export utility — generates a human-readable DDL file from the
SQLAlchemy metering metadata.

Run from the repo root:
    python -m backend.metering.schema.export

Outputs: backend/metering/schema/metering_schema.sql

Commit this file alongside any changes to models/tables.py.
CI can verify no drift between tables.py and the committed SQL by
running this script and checking `git diff`.
"""
from __future__ import annotations

import sys
from pathlib import Path

from sqlalchemy.schema import CreateIndex, CreateTable
from sqlalchemy.dialects import postgresql

from backend.metering.models.tables import (
    configure_schema,
    metering_cost_rates,
    metering_llm_interactions,
    metering_metadata,
    metering_operations,
)

_OUT = Path(__file__).parent / "metering_schema.sql"
_SCHEMA = "dynamoui_internal"


def export_ddl(schema: str = _SCHEMA) -> str:
    configure_schema(schema)
    dialect = postgresql.dialect()
    lines: list[str] = [
        f"-- DynamoUI internal schema DDL",
        f"-- Generated by: python -m backend.metering.schema.export",
        f"-- Source of truth: backend/metering/models/tables.py",
        f"-- DO NOT EDIT MANUALLY — regenerate after changing tables.py",
        "",
        f"CREATE SCHEMA IF NOT EXISTS {schema};",
        "",
    ]

    for table in (metering_cost_rates, metering_operations, metering_llm_interactions):
        ddl = str(CreateTable(table).compile(dialect=dialect))
        lines.append(ddl.strip() + ";")
        lines.append("")

    for table in (metering_cost_rates, metering_operations, metering_llm_interactions):
        for index in table.indexes:
            idx_ddl = str(CreateIndex(index).compile(dialect=dialect))
            lines.append(idx_ddl.strip() + ";")
    lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    ddl = export_ddl()
    _OUT.write_text(ddl, encoding="utf-8")
    print(f"Written: {_OUT}")
